[package]
name = "meaning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
reqwest = "0.11.11"
tokio = { version = "1", features = ["full"] }

